# Generated by Django 5.2.1 on 2025-05-12 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('gameState', models.CharField(choices=[('Wait', 'Waiting on players'), ('Progress', 'Game in progress'), ('Finished', 'Finshed game')], default='Wait')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
