# Generated by Django 5.2.1 on 2025-05-12 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tictactoegame',
            old_name='creationTime',
            new_name='creation_time',
        ),
        migrations.RemoveField(
            model_name='tictactoegame',
            name='gameState',
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='game_board',
            field=models.CharField(default='---------', max_length=9),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='game_state',
            field=models.CharField(choices=[('Awaiting', 'Waiting on players'), ('Progress', 'Game in progress'), ('Finished', 'Finshed game')], default='Awaiting', max_length=8),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='opponent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='playerTurn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='winner',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tictactoegame',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cretor', to=settings.AUTH_USER_MODEL),
        ),
    ]
