# Generated by Django 5.2.1 on 2025-05-12 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_rename_creationtime_tictactoegame_creation_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tictactoegame',
            old_name='playerTurn',
            new_name='player_turn',
        ),
        migrations.AlterField(
            model_name='tictactoegame',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoegame',
            name='winner',
            field=models.BooleanField(null=True),
        ),
    ]
